# Generated by Django 5.1.6 on 2025-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bible_quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bibletranslation',
            unique_together={('translation', 'id', 'chapter', 'verse')},
        ),
        migrations.RemoveField(
            model_name='bibletranslation',
            name='book_id',
        ),
    ]
